name: Build Kivy APK (manual SDK install)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Disable Docker BuildKit
      run: echo "DOCKER_BUILDKIT=0" >> $GITHUB_ENV

    - name: Run Buildozer Docker
      uses: addnab/docker-run-action@v3
      with:
        image: kivy/buildozer
        options: -v ${{ github.workspace }}:/app
        run: |
          buildozer android debug
