name: Build Kivy APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
            libgstreamer1.0 libgstreamer-plugins-base1.0 ffmpeg libtool

      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade buildozer
          pip install cython==0.29.26

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('**/buildozer.spec') }}

      - name: Prepare Android SDK & cmdline-tools
        run: |
          find ~/.buildozer/android/platform/android-sdk -name '*.zip' \
            -exec unzip -o -d ~/.buildozer/android/platform/android-sdk {} \;
          cd ~/.buildozer/android/platform/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmd.zip
          unzip -o cmd.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools cmdline-tools/latest

      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          repository_root: .
          workdir: .
          buildozer_version: stable
          command: |
            export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
            yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: vyatsu-news-apk
          path: ${{ steps.buildozer.outputs.filename }}
